language: python
services:
- redis-server
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_ef9407a88c9b_key -iv $encrypted_ef9407a88c9b_iv
  -in authorized_keys.enc -out ~/.ssh/authorized_keys -d
install:
- pip install -r requirements.txt
- pip install coverage
- pip install coveralls
script:
- coverage run --source='.' --omit=venv/*,*/migrations/*,*_init__.py,joinour/* manage.py test
- coverage report
after_success:
- coveralls
# - ssh root@47.93.188.227 "~/build.ssh"
add_ones:
  ssh_known_hosts:47.93.188.227
