language: python
services:
  - redis-server
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source='.' --omit=venv/*,*/migrations/*,*_init__.py,joinour/* manage.py test
  - coverage report
after_success:
  - coveralls
