language: python
services:
  - redis-server
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - python manage.py test cms
  - coverage run --source='.' --omit=venv/*,cms/migrations/*,*_init__.py manage.py test cms
  - coverage report