language: python
services:
  - redis-server
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - coverage run --source='.' --omit=venv/*,*/migrations/*,*_init__.py manage.py test
  - coverage report